### ISSUE TITLE
wrong validation rectangle  position in the report screenshot 

### ISSUE THREAD

**Issue by mondy2002** [ShaftHQ/using_SHAFT_Engine#40]
when I validate the login  function 
 i expect the rectangle in the screenshot should cover (welcome to manager page of guru 99 Bank)
 but the rectangle covers area above this statement 
[test.zip](https://github.com/MohabMohie/using_SHAFT_Engine/files/10737471/test.zip)
![image](https://user-images.githubusercontent.com/99874168/218879128-402d4ec3-16aa-4b41-8667-8944e245c12b.png)
![image](https://user-images.githubusercontent.com/99874168/218879165-65b2aed4-7134-4829-95c3-ee925dae0bf5.png)
![image](https://user-images.githubusercontent.com/99874168/218879206-b66707b1-ba54-4c79-a38c-0c7ba56032dd.png)

![image](https://user-images.githubusercontent.com/99874168/218879231-9efc77c3-4a9e-4744-93ea-97c3df560c7d.png)

**Comment by MohabMohie** [comment]
@mondy2002 if this is still an issue, please note that we support SHAFT_Engine issues via the official https://github.com/ShaftHQ/SHAFT_ENGINE project.

for this specific issue, kindly note that this has to do with your windows scaling factor.
check the scaling settings for your OS and use this property `screenshotParams_scalingFactor` to configure it properly
https://shafthq.github.io/docs/Properties/PropertiesList#visualvalidations
<img width="697" alt="image" src="https://github.com/ShaftHQ/using_SHAFT_Engine/assets/19201898/7e28d4e0-50c9-4561-8767-83e9a90c8d75">
